canadian_etfs_parsed:
- BRK
- BXF.TO
- CBD.TO
- CBH.TO
- CBN.TO
- CBO.TO
- CDZ.TO
- CEW.TO
- CGL.TO
- CGR.TO
- CHB.TO
- CIF.TO
- CLF.TO
- CLG.TO
- CMR.TO
- COW.TO
- CPD.TO
- CSD.TO
- CUD.TO
- CVD.TO
- CWW.TO
- CXF.TO
- CYH.TO
- DLR.TO
- DXM.TO
- ELV.TO
- ETP.TO
- EUR.TO
- FDE.TO
- FDV.TO
- FDY.TO
- FHB.TO
- FHC.TO
- FHD.TO
- FHE.TO
- FHF.TO
- FHG.TO
- FHH.TO
- FHM.TO
- FHQ.TO
- FHU.TO
- FIE.TO
- FLI.TO
- FSL.TO
- FUD.TO
- FXM.TO
- HAB.TO
- HAC.TO
- HAD.TO
- HAF.TO
- HAJ.TO
- HAL.TO
- HAZ.TO
- HBA.TO
- HBB.TO
- HBD.TO
- HBU.TO
- HCA.TO
- HEA.TO
- HED.TO
- HEE.TO
- HEF.TO
- HEJ.TO
- HEP.TO
- HEU.TO
- HEW.TO
- HEX.TO
- HFD.TO
- HFG.TO
- HFP.TO
- HFR.TO
- HFT.TO
- HFU.TO
- HGD.TO
- HGU.TO
- HGY.TO
- HHF.TO
- HIU.TO
- HIX.TO
- HMF.TO
- HND.TO
- HNU.TO
- HNY.TO
- HOD.TO
- HOG.TO
- HOU.TO
- HPR.TO
- HQD.TO
- HQU.TO
- HSD.TO
- HSL.TO
- HSU.TO
- HUC.TO
- HUF.TO
- HUG.TO
- HUM.TO
- HUN.TO
- HUT.TO
- HUV.TO
- HUZ.TO
- HVI.TO
- HVU.TO
- HXD.TO
- HXE.TO
- HXF.TO
- HXS.TO
- HXT.TO
- HXU.TO
- HYI.TO
- HZD.TO
- HZU.TO
- ILV.TO
- KILO.TO
- MXF.TO
- PBD.TO
- PBI.TO
- PDC.TO
- PDF.TO
- PFL.TO
- PHE.TO
- PHR.TO
- PIN.TO
- PMM.TO
- PPS.TO
- PRA.TO
- PSA.TO
- PSB.TO
- PTB.TO
- PUD.TO
- PXC.TO
- QCD.TO
- QEM.TO
- QGL.TO
- QIE.TO
- QMA.TO
- QMY.TO
- QQC.TO
- QQC.F
- QQQ
- QUS.TO
- QXM.TO
- RBO.TO
- RCD.TO
- RID.TO
- RIT.TO
- RPD.TO
- RQF.TO
- RQH.TO
- RQI.TO
- RUD.TO
- RWC.TO
- RWE.TO
- RWU.TO
- RWW.TO
- RXD.TO
- RY
- SVR.TO
- TD
- TLV.TO
- TXF.TO
- ULV.TO
- USB.TO
- UXM.TO
- VA.TO
- VAB.TO
- VBG.TO
- VBU.TO
- VCE.TO
- VCN.TO
- VDU.TO
- VDY.TO
- VE.TO
- VEE.TO
- VEF.TO
- VFV.TO
- VFV
- VGG.TO
- VGH.TO
- VIU.TO
- VRE.TO
- VSB.TO
- VSC.TO
- VSP.TO
- VUN.TO
- VUS.TO
- VXC.TO
- VXM.TO
- WXM.TO
- XAW.TO
- XBB.TO
- XBM.TO
- XCB.TO
- XCD.TO
- XCG.TO
- XCS.TO
- XCV.TO
- XDV.TO
- XEB.TO
- XEC.TO
- XEF.TO
- XEG.TO
- XEH.TO
- XEI.TO
- XEM.TO
- XEN.TO
- XEQT.TO
- XEU.TO
- XFN.TO
- XFT
- XFR.TO
- XGB.TO
- XGD.TO
- XGI.TO
- XHC.TO
- XHD.TO
- XIC.TO
- XIN.TO
- XIT.TO
- XIU.TO
- XLB.TO
- XMA.TO
- XMD.TO
- XMI.TO
- XMM.TO
- XMU.TO
- XMV.TO
- XMW.TO
- XQB.TO
- XQQ.TO
- XRB.TO
- XRE.TO
- XSB.TO
- XSH.TO
- XSP.TO
- XSQ.TO
- XST.TO
- XSU.TO
- XTR.TO
- XUS.TO
- XUT.TO
- XUU.TO
- XWD.TO
- XXM.TO
- YXM.TO
- ZAG.TO
- ZBK.TO
- ZCH.TO
- ZCM.TO
- ZCN.TO
- ZCS.TO
- ZDB.TO
- ZDI.TO
- ZDJ.TO
- ZDM.TO
- ZDV.TO
- ZDY.TO
- ZEA.TO
- ZEB.TO
- ZEF.TO
- ZEM.TO
- ZEO.TO
- ZEQ.TO
- ZFH.TO
- ZFL.TO
- ZFM.TO
- ZFS.TO
- ZGD.TO
- ZGI.TO
- ZGQ.TO
- ZHY.TO
- ZIC.TO
- ZID.TO
- ZIN.TO
- ZJG.TO
- ZJN.TO
- ZJO.TO
- ZLB.TO
- ZLC.TO
- ZLU.TO
- ZMI.TO
- ZMP.TO
- ZMT.TO
- ZMU.TO
- ZPL.TO
- ZPR.TO
- ZPS.TO
- ZQQ.TO
- ZRE.TO
- ZRR.TO
- ZSP.TO
- ZST.TO
- ZSU.TO
- ZUB.TO
- ZUD.TO
- ZUE.TO
- ZUH.TO
- ZUQ.TO
- ZUT.TO
- ZWA.TO
- ZWB.TO
- ZWH.TO
- ZWU.TO
- ZXM.TO